language: c

branches:
  only:
    - master
    - release

sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - STABLE_VERSION="0.0.1"

install:
  - bash .travis_install.bash

script:
  - make test
