version: 2.1

orbs:
  zulip: ponylang/zulip@1.0.0

jobs:
  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test
      - zulip/status:
          fail_only: true

  vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make test
      - zulip/status:
          fail_only: true

workflows:
  version: 2.1
  commit:
    jobs:
      - vs-ponyc-master:
          context: org-global

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master:
          context: org-global
