name: Nightly breakage against ponyc:latest

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  vs-ponyc-master:
    name: Verify master against ponyc:latest
    runs-on: ubuntu-latest
    container:
      image: ponylang/ponyc:latest
    steps:
      - uses: actions/checkout@v1
      - name: Test with ponyc:latest
        run: make test
