name: Release

on:
  push:
    tags:
      - \d+.\d+.\d+

jobs:
  x86-64-unknown-linux-release:
    name: Build and upload x86-64-unknown-linux-release to Cloudsmith
    runs-on: ubuntu-latest
    container:
      image: ponylang/shared-docker-ci-x86-64-unknown-linux-builder:release
    steps:
      - uses: actions/checkout@v1
      - name: Build and upload
        run: bash .ci-scripts/release/x86-64-unknown-linux-release.bash
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

  x86-64-apple-darwin-release:
    name: Build and upload x86-64-apple-darwin-release to Cloudsmith
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install pony tools
        run: bash .ci-scripts/install-macOS-tools.bash
      - name: brew install dependencies
        run: brew install coreutils
      - name: pip install dependencies
        run: pip3 install --upgrade cloudsmith-cli
      - name: Build and upload
        run: bash .ci-scripts/release/x86-64-apple-darwin-release.bash
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}

  build-release-docker-images:
    name: Build and push release Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash .ci-scripts/release/build-docker-images-on-release.bash

  trigger-release-announcement:
    needs: [x86-64-unknown-linux-release, x86-64-apple-darwin-release, build-release-docker-images]

    name: Trigger release announcement
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Trigger
        uses: ponylang/release-bot-action@0.3.3
        with:
          step: trigger-release-announcement
          git_user_name: "Ponylang Main Bot"
          git_user_email: "ponylang.main@gmail.com"
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  send-release-event:
    needs: [x86-64-unknown-linux-release, x86-64-apple-darwin-release, build-release-docker-images]

    name: Send release event
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['ponylang/shared-docker']
    steps:
      - name: Send
        uses: ponylang-main/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
        with:
          token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: changelog-tool-released
          client-payload: '{}'
